{
 "title": "kafka2",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Under-Replicated Partitions ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_underreplicatedpartitions",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Topics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_globaltopiccount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesin_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesout_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}